/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AcesseNossoGrupoRouteImport } from './routes/acesse-nosso-grupo'
import { Route as IndexRouteImport } from './routes/index'

const AcesseNossoGrupoRoute = AcesseNossoGrupoRouteImport.update({
  id: '/acesse-nosso-grupo',
  path: '/acesse-nosso-grupo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acesse-nosso-grupo': typeof AcesseNossoGrupoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acesse-nosso-grupo': typeof AcesseNossoGrupoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acesse-nosso-grupo': typeof AcesseNossoGrupoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/acesse-nosso-grupo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/acesse-nosso-grupo'
  id: '__root__' | '/' | '/acesse-nosso-grupo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcesseNossoGrupoRoute: typeof AcesseNossoGrupoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/acesse-nosso-grupo': {
      id: '/acesse-nosso-grupo'
      path: '/acesse-nosso-grupo'
      fullPath: '/acesse-nosso-grupo'
      preLoaderRoute: typeof AcesseNossoGrupoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcesseNossoGrupoRoute: AcesseNossoGrupoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
